import datasend
import asyncio
import time

body = []

async def main(body):
    serversender = datasend.ServerSender()
    response = await serversender.send_to_server(body)
    print(response)
    return response

while True:
    # some AI process creates body
    new_data = [{'plate':'12 AB 2021', 'date':'10/06/2023 14:30'}] # note the list of dicts
    body.extend(new_data)  # assuming new_data is the new data generated by the AI process

    response = asyncio.run(main(body))
    if response == 201:
        print('her sey basarılı')
        body = []
    else:
        print("Error sending data to server")
    time.sleep(10)